//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentskaSluzbaGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentskaSluzbaGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaciji.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjenja.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi ocenu.
        /// </summary>
        internal static string CancelGrade {
            get {
                return ResourceManager.GetString("CancelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrvdi.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna godina studija.
        /// </summary>
        internal static string CurrentYearOfStudy {
            get {
                return ResourceManager.GetString("CurrentYearOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedra.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra katedre.
        /// </summary>
        internal static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv katedre.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno ESPB.
        /// </summary>
        internal static string ESPB {
            get {
                return ResourceManager.GetString("ESPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ESPB bodova.
        /// </summary>
        internal static string ESPBNumber {
            get {
                return ResourceManager.GetString("ESPBNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godine staža.
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosečna ocena.
        /// </summary>
        internal static string GPA {
            get {
                return ResourceManager.GetString("GPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šef katedre.
        /// </summary>
        internal static string HeadOfDepartment {
            get {
                return ResourceManager.GetString("HeadOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj šefa katedre.
        /// </summary>
        internal static string HeadOfDepartmentAdd {
            get {
                return ResourceManager.GetString("HeadOfDepartmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj licne karte.
        /// </summary>
        internal static string IdCard {
            get {
                return ResourceManager.GetString("IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar izvodjenja.
        /// </summary>
        internal static string MaintainingSemester {
            get {
                return ResourceManager.GetString("MaintainingSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina izvodjenja.
        /// </summary>
        internal static string MaintainingYear {
            get {
                return ResourceManager.GetString("MaintainingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacin finansiranja.
        /// </summary>
        internal static string MethodOfFinancing {
            get {
                return ResourceManager.GetString("MethodOfFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa kancelarije.
        /// </summary>
        internal static string OfficeAdress {
            get {
                return ResourceManager.GetString("OfficeAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanja profesora.
        /// </summary>
        internal static string ProfessorAdd {
            get {
                return ResourceManager.GetString("ProfessorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena profesora.
        /// </summary>
        internal static string ProfessorChange {
            get {
                return ResourceManager.GetString("ProfessorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id profesora.
        /// </summary>
        internal static string ProfessorId {
            get {
                return ResourceManager.GetString("ProfessorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori.
        /// </summary>
        internal static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izadji.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa stanovanja.
        /// </summary>
        internal static string ResidentialAddress {
            get {
                return ResourceManager.GetString("ResidentialAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacuvaj.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje studenta.
        /// </summary>
        internal static string StudentAdd {
            get {
                return ResourceManager.GetString("StudentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena studenta.
        /// </summary>
        internal static string StudentChange {
            get {
                return ResourceManager.GetString("StudentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska služba.
        /// </summary>
        internal static string StudentService {
            get {
                return ResourceManager.GetString("StudentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje predmeta.
        /// </summary>
        internal static string SubjectAdd {
            get {
                return ResourceManager.GetString("SubjectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra predmeta.
        /// </summary>
        internal static string SubjectCode {
            get {
                return ResourceManager.GetString("SubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv predmeta.
        /// </summary>
        internal static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položeni.
        /// </summary>
        internal static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaganje.
        /// </summary>
        internal static string TakingExam {
            get {
                return ResourceManager.GetString("TakingExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepoloženi.
        /// </summary>
        internal static string Unsubmitted {
            get {
                return ResourceManager.GetString("Unsubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina upisa.
        /// </summary>
        internal static string YearOfEnrollment {
            get {
                return ResourceManager.GetString("YearOfEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina studija.
        /// </summary>
        internal static string YearOfStudy {
            get {
                return ResourceManager.GetString("YearOfStudy", resourceCulture);
            }
        }
    }
}
